/**
 * PrescriptionReport.jsx — Final CDSS Clinical Report & Doctor Verification Portal
 * ===================================================================================
 * Displays:
 *  - Assessment & Differential Diagnoses
 *  - Repeat Visit Longitudinal Vitals Delta & Trend (if returning patient)
 *  - AI Suggested OTC care plan
 *  - CDSS Doctor / Nurse Verification & OPD Token Generation CTA
 *  - Disclaimer & Voice narration in Tamil
 */

import React, { useEffect, useRef } from 'react';
import { useTamilVoice } from '../hooks/useTamilVoice.js';
import LongitudinalComparison from './LongitudinalComparison.jsx';

const TRIAGE_CONFIG = {
  'Self-Care':         { color: 'green',  icon: '🏠', bg: 'from-green-900/40  to-emerald-900/20', border: 'border-green-700',  text: 'text-green-400'  },
  'See Doctor in 24h': { color: 'amber',  icon: '🏥', bg: 'from-amber-900/40  to-yellow-900/20',  border: 'border-amber-700',  text: 'text-amber-400'  },
  'Emergency':         { color: 'red',    icon: '🚨', bg: 'from-red-900/50    to-rose-900/30',     border: 'border-red-700',    text: 'text-red-400'    },
};

export default function PrescriptionReport({
  report,
  vitals,
  patient,
  pastVisits,
  triage: triageData,
  onNewScan,
  onRestart,
  onOpenDoctorModal,
  doctorToken,
}) {
  const { speak, isSpeaking } = useTamilVoice();
  const hasSpoken = useRef(false);

  // Auto-speak triage decision + assessment on load with Tamil Neural voice
  useEffect(() => {
    if (report && !hasSpoken.current) {
      hasSpoken.current = true;
      const msg = report.triage_tamil || report.triage_tanglish || report.assessment_tamil || '';
      if (msg) {
        setTimeout(() => speak(msg), 800);
      }
    }
  }, [report, speak]);

  if (!report) return null;

  const triage = TRIAGE_CONFIG[report.triage_decision] || TRIAGE_CONFIG['Self-Care'];

  return (
    <div className="space-y-5 animate-fade-in text-left">
      
      {/* ── Patient Profile Badge ───────────────────────────────────────────── */}
      {patient && (
        <div className="bg-slate-900/90 border border-slate-700/80 rounded-2xl p-4 flex items-center justify-between shadow-lg">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-violet-900/50 border border-violet-700 flex items-center justify-center text-lg">
              🪪
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-sm font-bold text-white">{patient.name}</span>
                <span className="text-xs text-cyan-400 font-mono">({patient.uhid})</span>
              </div>
              <p className="text-xs text-slate-400">
                {patient.age}y / {patient.gender} • {patient.phone || 'Walk-in'}
              </p>
            </div>
          </div>
          {doctorToken ? (
            <div className="text-right">
              <span className="px-3 py-1 rounded-full bg-emerald-950/70 border border-emerald-500 text-emerald-300 font-mono font-bold text-xs">
                ✓ {doctorToken.token_number}
              </span>
              <p className="text-[10px] text-emerald-400 mt-1">Doctor Verified</p>
            </div>
          ) : (
            <span className="px-2.5 py-1 rounded-full bg-amber-950/40 border border-amber-700 text-amber-300 text-xs">
              AI Draft (Pending Sign-off)
            </span>
          )}
        </div>
      )}

      {/* ── Header ──────────────────────────────────────────────────────────── */}
      <div className="text-center">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-violet-900/40 border border-violet-700 text-violet-300 text-xs font-semibold mb-2">
          🩺 CDSS Clinical Assessment Report
        </div>
        <h2 className="text-xl font-bold text-white">{report.assessment_title}</h2>
        <p className="text-xs text-slate-400 mt-1">{report.assessment_english}</p>
      </div>

      {/* ── Repeat Visit Longitudinal Comparison (if returning patient) ───── */}
      {pastVisits && pastVisits.length > 0 && (
        <LongitudinalComparison currentVitals={vitals} pastVisits={pastVisits} />
      )}

      {/* ── Longitudinal Trend Note (if generated by AI/backend) ────────────── */}
      {report.longitudinal_notes && (
        <div className="bg-cyan-950/30 border border-cyan-700/80 rounded-2xl p-4 flex items-start gap-3">
          <span className="text-xl">📊</span>
          <div>
            <p className="text-xs font-bold text-cyan-300 uppercase tracking-wider">
              Longitudinal Visit Intelligence
            </p>
            <p className="text-xs text-slate-200 mt-0.5">{report.longitudinal_notes}</p>
          </div>
        </div>
      )}

      {/* ── Doctor Verification CTA Card (Clinical Decision Support) ────────── */}
      <div className="bg-gradient-to-r from-violet-950/40 via-slate-900 to-cyan-950/40 border-2 border-violet-700/80 rounded-2xl p-5 shadow-2xl space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-violet-600/30 border border-violet-500 flex items-center justify-center text-xl">
              👨‍⚕️
            </div>
            <div>
              <h3 className="text-sm font-bold text-white">
                Doctor / Nurse Verification (சரிபார்ப்பு)
              </h3>
              <p className="text-xs text-violet-300">
                Human-in-the-loop validation • Order lab tests • Issue OPD Token
              </p>
            </div>
          </div>
          {doctorToken && (
            <span className="text-xl">✅</span>
          )}
        </div>

        {doctorToken ? (
          <div className="p-3 bg-emerald-950/30 border border-emerald-700/70 rounded-xl flex items-center justify-between text-xs">
            <div>
              <p className="font-bold text-emerald-300">
                Approved by {doctorToken.verified_data?.doctor_name}
              </p>
              <p className="text-slate-400 mt-0.5">
                Token: <strong className="text-white font-mono">{doctorToken.token_number}</strong> • {doctorToken.opd_room}
              </p>
            </div>
            <button
              type="button"
              onClick={onOpenDoctorModal}
              className="px-3 py-1.5 rounded-lg bg-emerald-700 hover:bg-emerald-600 text-white font-semibold text-xs shadow"
            >
              View / Print Slip
            </button>
          </div>
        ) : (
          <button
            type="button"
            onClick={onOpenDoctorModal}
            className="w-full py-3.5 px-4 rounded-xl font-bold text-sm bg-gradient-to-r from-violet-600 via-cyan-600 to-blue-600 hover:from-violet-500 hover:to-cyan-500 text-white shadow-xl shadow-violet-950/50 hover:scale-[1.01] active:scale-[0.98] transition-all flex items-center justify-center gap-2"
          >
            <span>👨‍⚕️</span>
            <span>மருத்துவர் சரிபார்ப்பு & OPD டோக்கன் பெறுக (Review & Sign-off)</span>
            <span>→</span>
          </button>
        )}
      </div>

      {/* ── Assessment Card (Tanglish) ──────────────────────────────────────── */}
      <div className="bg-slate-800/60 border border-slate-700 rounded-2xl p-5">
        <div className="flex items-start gap-3">
          <div className="w-10 h-10 rounded-full bg-gradient-to-br from-violet-500 to-cyan-500 flex items-center justify-center text-lg flex-shrink-0">
            🤖
          </div>
          <div className="flex-1">
            <p className="text-sm text-cyan-300 leading-relaxed mb-2">
              {report.assessment_tanglish}
            </p>
            <p className="text-xs text-slate-400 leading-relaxed" style={{ fontFamily: 'Noto Sans Tamil, sans-serif' }}>
              {report.assessment_tamil}
            </p>
          </div>
          <button
            type="button"
            onClick={() => speak(report.assessment_tamil || report.assessment_tanglish)}
            className={`w-8 h-8 rounded-full flex items-center justify-center text-sm flex-shrink-0 transition-all
              ${isSpeaking ? 'bg-violet-600 animate-pulse shadow-lg shadow-violet-900/50' : 'bg-slate-700 hover:bg-slate-600'} text-slate-300`}
            title="Listen to Assessment (Tamil AI Voice)"
          >
            {isSpeaking ? '🔊' : '🔈'}
          </button>
        </div>
      </div>

      {/* ── Triage Decision ─────────────────────────────────────────────────── */}
      <div className={`bg-gradient-to-r ${triage.bg} border ${triage.border} rounded-2xl p-5`}>
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-3">
            <span className="text-3xl">{triage.icon}</span>
            <div>
              <p className="text-xs text-slate-400 uppercase tracking-widest">Triage Decision / முடிவு</p>
              <p className={`text-xl font-bold ${triage.text}`}>{report.triage_decision}</p>
            </div>
          </div>
          <button
            type="button"
            onClick={() => speak(report.triage_tamil || report.triage_tanglish)}
            className="px-3 py-1.5 rounded-lg bg-slate-800/80 text-xs text-slate-300 hover:bg-slate-700 transition-all border border-slate-700/50 flex items-center gap-1.5"
            title="Listen to Triage (Tamil AI Voice)"
          >
            <span>🔈</span>
            <span>கேளுங்கள்</span>
          </button>
        </div>
        <p className="text-sm text-slate-200 mb-1">{report.triage_tanglish}</p>
        <p className="text-xs text-slate-400" style={{ fontFamily: 'Noto Sans Tamil, sans-serif' }}>
          {report.triage_tamil}
        </p>
      </div>

      {/* ── Possible Conditions ─────────────────────────────────────────────── */}
      {report.possible_conditions?.length > 0 && (
        <div className="bg-slate-800/40 border border-slate-700 rounded-xl p-4">
          <h3 className="text-xs font-mono text-slate-400 uppercase tracking-widest mb-3">
            🔬 Differential Diagnoses (சாத்தியமான காரணங்கள்)
          </h3>
          <div className="flex flex-wrap gap-2">
            {report.possible_conditions.map((cond, idx) => (
              <span
                key={idx}
                className="px-3 py-1.5 rounded-full bg-blue-900/30 border border-blue-700 text-blue-300 text-xs font-medium"
              >
                {cond}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* ── Suggested Medicines ─────────────────────────────────────────────── */}
      {report.medicines?.length > 0 && (
        <div>
          <h3 className="text-xs font-mono text-slate-400 uppercase tracking-widest mb-3 px-1">
            💊 Recommended Medications (பரிந்துரைக்கப்பட்ட மருந்துகள்)
          </h3>
          <div className="space-y-3">
            {report.medicines.map((med, idx) => (
              <div
                key={idx}
                className="bg-slate-800/50 border border-slate-700 rounded-xl p-4"
              >
                <div className="flex items-start justify-between mb-2">
                  <p className="text-sm font-semibold text-white">{med.name}</p>
                  <span className="px-2 py-0.5 rounded-full bg-cyan-900/40 border border-cyan-700 text-cyan-300 text-xs">
                    {med.dosage}
                  </span>
                </div>
                <div className="grid grid-cols-2 gap-2 text-xs text-slate-400 mb-2">
                  <div>
                    <span className="text-slate-500">அளவு / முறை: </span>
                    <span className="text-slate-300 font-medium">{med.frequency}</span>
                  </div>
                  <div>
                    <span className="text-slate-500">கால அளவு: </span>
                    <span className="text-slate-300 font-medium">{med.duration || '3-5 நாட்கள்'}</span>
                  </div>
                </div>
                {med.reason && (
                  <p className="text-xs text-slate-400 mb-1.5 bg-slate-900/40 p-2 rounded-lg border border-slate-800">
                    <span className="text-slate-500 font-medium">பயன்: </span>
                    <span className="text-cyan-300">{med.reason}</span>
                  </p>
                )}
                {med.caution && (
                  <div className="flex items-start gap-1.5 mt-2 text-xs text-amber-300 bg-amber-950/30 p-2 rounded-lg border border-amber-900/50">
                    <span>⚠️</span>
                    <span>{med.caution}</span>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Home Care Tips ──────────────────────────────────────────────────── */}
      {report.home_care?.length > 0 && (
        <div className="bg-slate-800/40 border border-slate-700 rounded-xl p-4">
          <h3 className="text-xs font-mono text-slate-400 uppercase tracking-widest mb-3">
            🏠 Home Care Guidelines (வீட்டு பராமரிப்பு)
          </h3>
          <div className="space-y-2">
            {report.home_care.map((tip, idx) => (
              <div key={idx} className="flex items-start gap-2 text-xs text-slate-300">
                <span className="text-green-400 flex-shrink-0 mt-0.5">✓</span>
                <div>
                  <p>{tip}</p>
                  {report.home_care_tamil?.[idx] && (
                    <p className="text-[11px] text-slate-500 mt-0.5" style={{ fontFamily: 'Noto Sans Tamil, sans-serif' }}>
                      {report.home_care_tamil[idx]}
                    </p>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Follow Up ───────────────────────────────────────────────────────── */}
      {report.follow_up && (
        <div className="flex items-start gap-2 px-4 py-3 rounded-xl bg-violet-900/20 border border-violet-800 text-xs">
          <span className="text-violet-400">📅</span>
          <p className="text-violet-300">{report.follow_up}</p>
        </div>
      )}

      {/* ── Disclaimer ──────────────────────────────────────────────────────── */}
      <div className="px-4 py-3 rounded-xl bg-slate-900/50 border border-slate-800">
        <p className="text-[11px] text-slate-500 text-center leading-relaxed">
          ⚕️ {report.disclaimer}
        </p>
      </div>

      {/* ── Action Buttons ──────────────────────────────────────────────────── */}
      <div className="grid grid-cols-2 gap-3">
        <button
          type="button"
          onClick={onNewScan}
          className="py-3 px-4 rounded-xl text-xs font-semibold bg-slate-700 hover:bg-slate-600 text-slate-200 transition-all"
        >
          🔄 New Scan
        </button>
        <button
          type="button"
          onClick={onRestart}
          className="py-3 px-4 rounded-xl text-xs font-semibold bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white shadow-lg transition-all"
        >
          🏠 Back to Home
        </button>
      </div>
    </div>
  );
}
